module.exports = {
  0: "../BlockMan/images/empty_space.png",
  CAVE_FLOOR: "../BlockMan/images/cave_floor.png",
  CAVE_CEILING: "../BlockMan/images/cave_ceiling.png",
  CAVE_WEST_WALL: "../BlockMan/images/west_wall.png",
  CAVE_EAST_WALL: "../BlockMan/images/east_wall.png",
  NORTHEAST_CORNER: "../BlockMan/images/north_east_corner.png",
  SOUTHEAST_CORNER: "../BlockMan/images/south_east_corner.png",
  SOUTHWEST_CORNER: "../BlockMan/images/south_west_corner.png",
  NORTHWEST_CORNER: "../BlockMan/images/north_west_corner.png",
  2: "../BlockMan/images/block.png",
  RIGHT: "../BlockMan/images/right_sprite.png",
  LEFT: "../BlockMan/images/left_sprite.png",
  4: "../BlockMan/images/exit.png",
};
